ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "offensivePlays" JSONB;
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "defensivePlays" JSONB;

ALTER TABLE "Coach" ADD COLUMN IF NOT EXISTS "overall" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Coach" ADD COLUMN IF NOT EXISTS "offenseRating" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Coach" ADD COLUMN IF NOT EXISTS "defenseRating" INTEGER NOT NULL DEFAULT 60;
