ALTER TABLE "Player" DROP CONSTRAINT "Player_teamId_fkey";

ALTER TABLE "Player" ALTER COLUMN "teamId" DROP NOT NULL;

ALTER TABLE "Player"
ADD CONSTRAINT "Player_teamId_fkey"
FOREIGN KEY ("teamId") REFERENCES "Team"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
